import React from 'react';

export default function AdopterProfilePage() {
	return <div>
		fgggggggffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhf
		ghfgf fgggggggffffffffffffffffffffffffffffffffffffffffffffffffffff
		ghfgf fgggggggffffffffffffffffffffffffffffffffffffffffffffffffffff
		ghfgf fgggggggffffffffffffffffffffffffffffffffffffffffffffffffffff
		ghfgf fgggggggffffffffffffffffffffffffffffffffffffffffffffffffffff
		ghfgf fgggggggffffffffffffffffffffffffffffffffffffffffffffffffffff
		ghfgf fgggggggffffffffffffffffffffffffffffffffffffffffffffffffffff
		ghfgf fgggggggffffffffffffffffffffffffffffffffffffffffffffffffffff
		</div>;
}
