import { Shell } from '@/components/Shell';

export default async function IndexPage() {
	return (
		<Shell className="">
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
			sssssssssssssssssssssssssssssssssssssss fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
		  
		</Shell>
	);
}
