import '@/styles/globals.css';
import { GeistMono } from 'geist/font/mono';
import { GeistSans } from 'geist/font/sans';
import { cn } from '@/lib/utils';
import { Viewport, type Metadata } from 'next';

import { TRPCReactProvider } from '@/trpc/react';
import { fontHeading } from '@/lib/fonts';
import { ThemeProvider } from '@/components/ThemeProvider';
import { Toaster } from '@/components/ui/toaster';
import SessionWrapper from '@/components/SessionWrapper';
import { Analytics } from '@/components/analytics';
import { TailwindIndicator } from '@/components/tailwind-indicator';

export const metadata: Metadata = {
	title: 'Create T3 App',
	description: 'Generated by create-t3-app',
	icons: [ { rel: 'icon', url: '/favicon.ico' } ],
};

export const viewport: Viewport = {
	colorScheme: 'dark light',
	themeColor: [
		{ media: '(prefers-color-scheme: light)', color: 'white' },
		{ media: '(prefers-color-scheme: dark)', color: 'black' },
	],
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={cn(
					'min-h-screen bg-background font-sans antialiased',
					GeistSans.variable,
					GeistMono.variable,
					fontHeading.variable
				)}
			>
				<SessionWrapper>
					<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
						<TRPCReactProvider>{children}</TRPCReactProvider>
						<TailwindIndicator />
						<Analytics />
					</ThemeProvider>
				</SessionWrapper>
				<Toaster position="top-right" richColors closeButton />
			</body>
		</html>
	);
}
