-- CreateEnum
CREATE TYPE "PRODUCT_STATUS" AS ENUM ('AVAILABLE', 'OUT_OF_STOCK', 'DISCONTINUED');

-- AlterTable
ALTER TABLE "products" ADD COLUMN     "status" "PRODUCT_STATUS" NOT NULL DEFAULT 'AVAILABLE';
